kind: pipeline
name: default
steps:

  - name: install
    image: beamaustralia/php:7.3.6
    commands:
      - composer install --prefer-dist

  - name: test
    image: beamaustralia/php:7.3.6-xdebug
    commands:
      - vendor/bin/phpunit --coverage-clover clover.xml
    environment:
      ES_HOST: elasticsearch:9200

  - name: coverage
    image: beamaustralia/php:7.3.6
    commands:
      - vendor/bin/php-coveralls -v -x clover.xml -o coveralls.json
    environment:
      COVERALLS_RUN_LOCALLY:
        from_secret: COVERALLS_RUN_LOCALLY
      COVERALLS_REPO_TOKEN:
        from_secret: COVERALLS_REPO_TOKEN


services:
  - name: elasticsearch
    image: elasticsearch:5-alpine
