kind: pipeline
name: default
steps:

  - name: install
    image: beamaustralia/php:7.3.6
    commands:
      - composer install --prefer-dist

  - name: test
    image: beamaustralia/php:7.3.6-xdebug
    commands:
      - vendor/bin/phpunit --coverage-clover clover.xml
      - vendor/bin/php-coveralls -v --coverage_clover clover.xml
    environment:
      ES_HOST: elasticsearch:9200

services:
  - name: elasticsearch
    image: elasticsearch:5-alpine
