version: "3.7"
services:

  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"

  php:
    image: beamaustralia/php:7.3.6-xdebug
    volumes:
      - "./:/var/www"
    depends_on:
      - elasticsearch
    environment:
      - ES_HOST=elasticsearch:9200
